/* license section

   Aii is free software: you can redistribute it and/or modify   it under the terms of the GNU General Public License as published by   the Free Software Foundation, either version 3 of the License, or   (at your option) any later version.   Aii is distributed in the hope that it will be useful,   but WITHOUT ANY WARRANTY; without even the implied warranty of   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the   GNU General Public License for more details.   You should have received a copy of the GNU General Public License   along with Aii.  If not, see <http://www.gnu.org/licenses/>.   © Swfdong 2010 */ //校内工具类,用不显示的HTML Holder实现Ajax查询等功能package aii.net.xiaonei {	import flash.events.Event;	import flash.net.navigateToURL;	import flash.net.URLLoader;	import flash.net.URLRequest;	import flash.net.URLRequestMethod;	import flash.net.URLRequestHeader;	import flash.net.URLVariables;	import flash.system.System;	import flash.utils.Dictionary;	import flash.utils.getTimer;	import aii.utils.Logger;	import aii.utils.StringUtil;
	public final class XNMobileGadget {		//设置默认起始页(设置页面内容为空的friendsSelector.do以节省内存开销)		private static const XN_UA:String = "Aii XNMobileGadget [By Swfdong]";		private static const DEFAULT_URL:String = "http://3g.renren.com/home.do";		private static const POSITION_DICT:Dictionary = new Dictionary();		private static const CHEAT_REFERER:URLRequestHeader = new URLRequestHeader("Referer", "http://3g.renren.com/Home.do");		private var _loggedIn:Boolean = false;		private var _ticket:String;		private var _infoID:String;		private var _updateStatusCallback:Function;		private var _infoCallback:Function;		private var _searchCallback:Function;		private var _friendsCallback:Function;		private var _getGossipCallback:Function;		private var _sendGossipCallback:Function;		private var _id:String;		private var loginURL:String;		private var reqURL:String;		private var urlLoader:URLLoader;		private var urlRequest:URLRequest;		private var requestCallback:Function;		private var requestCount:uint = 0;		private var waitingContent:String;
		//初始化		public function XNMobileGadget():void {			urlRequest = new URLRequest();			urlRequest.data = null;			urlRequest.userAgent = XN_UA;			urlRequest.requestHeaders = [ CHEAT_REFERER ];			urlRequest.followRedirects = true;			urlRequest.manageCookies = true;			urlLoader = new URLLoader();			POSITION_DICT["101"] = "课堂";			POSITION_DICT["102"] = "床上";			POSITION_DICT["103"] = "公车";			POSITION_DICT["104"] = "街上";			POSITION_DICT["105"] = "餐厅";			POSITION_DICT["106"] = "公司";			POSITION_DICT["107"] = "户外";			POSITION_DICT["108"] = "锻炼";		}
		//跳转		public function redirect(u:String):void {			urlRequest.url = u;			navigateToURL(urlRequest, "_blank");		}
		//登录		public function login(u:String, p:String):void {			_loggedIn = false;			Logger.warn("[XNMobileGadget]手机端连接尚未登录，登录中...");			urlRequest.data = new URLVariables();			urlRequest.data.origURL = "/home.do";			urlRequest.data.email = u;			urlRequest.data.password = p;			request("http://3g.renren.com/login.do?fx=0&amp;autoLogin=true", loginCallBack);		}
		private function loginCallBack(data:String):void {			var ss:int = data.indexOf("sid=") + 4;			var se:int = data.indexOf("&", ss);			//获取存根			_ticket = data.substring(ss, se);			loginURL = DEFAULT_URL + "?sid=" + _ticket;			_loggedIn = true;			Logger.log("[XNMobileGadget]手机端已登录")		}
		//修改状态		public function updateStatus(s:String, callBack:Function):void {			//刷新			_updateStatusCallback = callBack;			waitingContent = s;			request(loginURL, updateStatusStep);			Logger.log("[XNMobileGadget]尝试修改状态为：“" + s + "”，正在抓取页面...");		}
		//获取刷新后内容并更新状态		public function updateStatusStep(data:String):void {			var ss:int = data.indexOf("wUpdateStatus.do?");			var se:int = data.indexOf('"', ss);			var tu:String = data.substring(ss, se);			urlRequest.data = new URLVariables();			urlRequest.data.status = waitingContent;			urlRequest.data.sour = "home";			urlRequest.data.update = "更新";			urlRequest.data.position = 101 + ((Math.random() * 8) >> 0);			request("http://3g.renren.com/status/" + tu, updateStatusCallback);			Logger.log("[XNMobileGadget]随机位置为" + POSITION_DICT[urlRequest.data.position] + "，请求发送中...");		}
		private function updateStatusCallback(data:String):void {			waitingContent = null;			Logger.log("[XNMobileGadget]状态已更改");			//_updateStatusCallback(data);			System.gc();		}
		//请求核心方法(若有data则自动转换为post)		private function request(u:String, callBack:Function = null):void {			urlRequest.url = reqURL = u;			urlRequest.method = (urlRequest.data == null ? URLRequestMethod.GET : URLRequestMethod.POST);			if (callBack != null) {				requestCallback = callBack;			}			urlLoader.load(urlRequest);			urlLoader.addEventListener(Event.COMPLETE, requestHandler);		}
		//回馈处理		private function requestHandler(e:Event):void {			//删除侦听			urlLoader.removeEventListener(Event.COMPLETE, requestHandler);			urlRequest.data = null;			requestCount = 0;			if (urlLoader.data != "" && requestCallback != null) {				requestCallback(urlLoader.data);			}		}	}}